job:
  url: http://127.0.0.1:8081
  checkCron: 0 */1 * * * * # once 1 minute

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.springframework.data: INFO
    com.oscar: INFO
