spring:
  profiles:
    active: local

server:
  port: 8082

job:
  type: 10
  podName: oscar-downloader-1
  checkCron: 0 */1 * * * * # once a minute

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.springframework.transaction.interceptor: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.springframework.data: INFO
    com.oscar: INFO

